getBizzy/urls.py
# """
# URL configuration for getBizzy project.
#


from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [

    path('', include('issues.urls')),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('api/', include('issues.urls')),
    path('token/',
              jwt_views.TokenObtainPairView.as_view(),
              name ='token_obtain_pair'),
    path('token/refresh/',
              jwt_views.TokenRefreshView.as_view(),
              name ='token_refresh')
]

issues/urls.py
# issues/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter
from issues.views import EntryViewSet, CreateIssueView
from rest_framework import routers

# Initialize the router
router = DefaultRouter()
router.register(r'entries', EntryViewSet)
router.register('entries/mine', EntryViewSet, basename='user-entries')

# List the router and your custom urlpatterns
urlpatterns = [
    path('', include(router.urls)),
    path('create-issue/', CreateIssueView.as_view(), name='create-issue'),
    path('home/', views.HomeView.as_view(), name ='home'),
    path('logout/', views.LogoutView.as_view(), name ='logout'),
    path('api/assistant/', views.assistant_response, name='assistant-response'),
 ]

issues/models.py
# models.py

from django.db import models
from django.contrib.auth.models import User
import uuid



class Entry(models.Model):
    """Model representing template content."""
    title = models.CharField(max_length=200)
    content = models.TextField('Content', help_text='Enter the Markdown content for the page.')
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

issues/forms.py
from django import forms

issues/views.py
# issues/views.py
from rest_framework.decorators import api_view
import openai
import os
from dotenv import load_dotenv
from django.urls import reverse, reverse_lazy
from django.views import generic
from rest_framework import serializers, status, viewsets
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Entry
from .serializers import EntrySerializer, CreateIssueSerializer
from rest_framework import permissions
import requests

# Load environment variables
load_dotenv()

# Initialize OpenAI
openai.api_key = os.getenv('OPENAI_API_KEY')
model = os.getenv('OPENAI_API_MODEL')

@api_view(['POST'])
def assistant_response(request):
    try:
        prompt = request.data.get('prompt', '')
        if not prompt:
            return Response({'error': 'No prompt provided'}, status=400)

        response = openai.Completion.create(
            model=model,
            prompt=prompt,
            max_tokens=100
        )

        return Response({'result': response.choices[0].text.strip()})
    except Exception as e:
        return Response({'error': str(e)}, status=500)

class IsCreatorOrReadOnly(permissions.BasePermission):
    """
    Custom permission to only allow the creator of an entry to edit or delete it.
    Other authenticated users can only view the entries.
    """
    def has_object_permission(self, request, view, obj):
        # SAFE_METHODS are read-only methods (GET, HEAD, OPTIONS)
        if request.method in permissions.SAFE_METHODS:
            return True
        # Only the creator of the entry can modify it
        return obj.creator == request.user

class EntryViewSet(viewsets.ModelViewSet):
    permission_classes = [IsCreatorOrReadOnly, IsAuthenticated]
    serializer_class = EntrySerializer
    queryset = Entry.objects.all()

    def get_queryset(self):
        # Filter to only show entries belonging to the authenticated user
        return Entry.objects.filter(creator=self.request.user)

    def perform_create(self, serializer):
        # Automatically assign the authenticated user as the creator
        serializer.save(creator=self.request.user)

# Other Views and Utility APIs
class CreateIssueView(APIView):
    def post(self, request, *args, **kwargs):
        serializer = CreateIssueSerializer(data=request.data)
        if serializer.is_valid():
            data = serializer.validated_data
            repo_path = data['repo_url'].split('gitlab.com/')[-1]

            headers = {
                'Private-Token': data['access_token']
            }
            issue_data = {
                'title': data['title'],
                'description': data['description'],
                'labels': ','.join(data['labels'])
            }

            response = requests.post(
                f'https://gitlab.com/api/v4/projects/{repo_path}/issues',
                headers=headers,
                data=issue_data
            )

            if response.status_code == 201:
                return Response({'message': 'Issue created successfully!'}, status=status.HTTP_201_CREATED)
            else:
                return Response({'message': 'Failed to create issue on GitLab'}, status=response.status_code)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class HomeView(APIView):
    permission_classes = (IsAuthenticated,)
    def get(self, request):
        content = {'message': 'Welcome to the Authentication page using React Js and Django!'}
        return Response(content)

class LogoutView(APIView):
    permission_classes = (IsAuthenticated,)
    def post(self, request):
        try:
            refresh_token = request.data["refresh_token"]
            token = RefreshToken(refresh_token)
            token.blacklist()
            return Response(status=status.HTTP_205_RESET_CONTENT)
        except Exception as e:
            return Response(status=status.HTTP_400_BAD_REQUEST)

class EntryListView(generic.ListView):
    model = Entry
    permission_classes = [IsAuthenticated]


class EntryCreate(generic.CreateView):
    model = Entry
    fields = '__all__'
    initial = {'Title': 'Enter the Markdown content for the page.'}

class EntryUpdate(generic.UpdateView):
    model = Entry
    fields = ['title', 'content']

class EntryDelete(generic.DeleteView):
    model = Entry
    success_url = reverse_lazy('index')

issues/templates/issues/add.html
{% extends "issues/layout.html" %}

{% block title %}
New Page - Templates
{% endblock %}

{% block body %}
<div class="container mt-4">
    <h1 class="display-4 mb-4">Create New Template</h1>
    <p class="mb-4">Enter the title and content for your new template entry. Use Markdown for formatting.</p>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="id_title" class="form-label">Title:</label>
            <input type="text" name="title" id="id_title" class="form-control" value="{{ title }}" required>

        </div>
        <div class="form-group mb-3">
            <label for="id_content" class="form-label">Content:</label>
            <textarea name="content" id="id_content" class="form-control" rows="10" required></textarea>
            <small class="form-text text-muted">
                Supports Markdown formatting. For help with Markdown, see the
                <a href="https://www.markdownguide.org/basic-syntax/" target="_blank">Markdown guide.</a>
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

issues/templates/issues/delete.html
{% extends "issues/layout.html" %}

{% block title %}
Delete {{ title }}
{% endblock %}

{% block body %}
<div class="container mt-4">
    <h1 class="display-4 mb-4">Delete {{ title }}</h1>
    <p>Are you sure you want to delete "{{ title }}"?</p>
    <form action="{% url 'delete' title=title %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

issues/templates/issues/edit.html
{% extends "issues/layout.html" %}

{% block title %}
Edit {{ title }}
{% endblock %}

{% block body %}
<div class="container mt-4">
    <h1 class="display-4 mb-4">Edit {{ title }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">Title:</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ title }}" />
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Content:</label>
            <textarea class="form-control" id="content" name="content" rows="10">{{ content }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>
{% endblock %}

issues/templates/issues/entry.html
{% extends "issues/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
<div class="container d-flex flex-column mt-4">
    <div class="flex-grow-1">
        <h1 class="display-4">{{ title }}</h1>
        <div class="mt-4">
            <div id="markdown-content">{{ entry|safe }}</div>
        </div>
    </div>
    <div class="mt-3">
        <a href="{% url 'edit' title=title %}" class="btn btn-primary">Edit Entry</a>
        <a href="{% url 'delete' title=title %}" class="btn btn-danger">Delete Entry</a>
    </div>
</div>
{% endblock %}

issues/templates/issues/error.html
{% extends "issues/layout.html" %}

{% block title %}
{{ title|default:"Search Results" }}
{% endblock %}

{% block body %}
<div class="container mt-4">
    <h1 class="display-4 mb-4">{{ title }}</h1>
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Template Not Found!</h4>
        <p>getBizzy does not have an template with this exact name. Here are some things you can try:</p>
        <ul>
            <li>Search for <strong><a href="{% url 'search' %}?q={{ title }}" class="alert-link">{{ title }}</a></strong> in Templates to check for alternative titles or spellings.</li>
            <li>Remember, titles on Templates are case sensitive. Please check for alternative capitalizations.</li>
        </ul>
        <p>Or, if you'd like, you can <a href="{% url 'add' %}?title={{ title }}" class="btn btn-primary">Create New Page</a> for "{{ title }}".</p>
    </div>
</div>
{% endblock %}

issues/templates/issues/error2.html
{% extends "issues/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
<div class="container mt-4">
    <h1 class="display-4 mb-4">{{ title }} - Duplicate Template Title</h1>
    <div class="alert alert-danger" role="alert">
        <p>getBizzy already has an template with this exact name. Please try a different title or <a href="{% url 'edit' title=title %}" class="alert-link">edit the existing article</a>.</p>
        <button onclick="history.back()" class="btn btn-primary">Go Back</button>
    </div>
</div>
{% endblock %}

issues/templates/issues/index.html
{% extends "issues/layout.html" %}

{% block title %}
Templates
{% endblock %}

{% block body %}
<div class="container mt-4">
    <h1 class="display-4 mb-4">All Templates</h1>
    <div class="list-group">
        {% for entry in entries %}
        <a href="{% url 'entry' entry %}" class="list-group-item list-group-item-action">{{ entry }}</a>
        {% endfor %}
    </div>
</div>
{% endblock %}

issues/templates/issues/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}getBizzy{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'styles.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Flamenco:wght@300;400&family=Inter:wght@100..900&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'favicon.ico' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row min-vh-100 flex-column flex-md-row">
        <aside class="col-12 col-md-3 col-lg-2 p-0 bg-dark flex-shrink-1">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark align-items-start flex-md-column flex-row">
                <a href="{% url 'index' %}" class="sidebar-logo"><img src="{% static 'logoWhite.png' %}" alt="Logo"></a>
                <form action="{% url 'search' %}" method="GET" class="w-100">
                    <div class="input-group">
                        <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search getBizzy" class="form-control">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </form>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="sidebarMenu">
                    <ul class="navbar-nav flex-column w-100 justify-content-start">
                        <li class="nav-item">
                            <a href="{% url 'index' %}" class="nav-link active">View Templates</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'add' %}" class="nav-link">Add Issue Template</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </aside>
        <main class="col bg-faded py-3 flex-grow-1">
            {% block body %}
            {% endblock %}
        </main>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/js/all.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

<script>
    function loadScript(url) {
        return new Promise((resolve, reject) => {
            const script = document.createElement("script");
            script.type = "text/javascript";
            script.onload = resolve;
            script.onerror = reject;
            script.src = url;
            document.head.appendChild(script);
        });
    }

    async function initializeMarkdownIt() {
        try {
            await loadScript("https://cdn.jsdelivr.net/npm/markdown-it/dist/markdown-it.min.js");
            await loadScript("https://cdn.jsdelivr.net/npm/markdown-it-emoji/dist/markdown-it-emoji.min.js");
            await loadScript("https://cdn.jsdelivr.net/npm/markdown-it-checkbox/dist/markdown-it-checkbox.min.js");

            const md = markdownit().use(markdownitEmoji).use(markdownitCheckbox);
            const markdownContent = document.getElementById('markdown-content');
            if (markdownContent) {
                const rawMarkdown = markdownContent.textContent || "No content loaded";
                markdownContent.innerHTML = md.render(rawMarkdown);
            } else {
                console.error("No markdown content element found.");
            }
        } catch (error) {
            console.error("Error loading scripts: ", error);
        }
    }

    document.addEventListener('DOMContentLoaded', initializeMarkdownIt);
</script>



</body>
</html>

issues/templates/issues/login.html
{% extends "issues/layout.html" %}

{% block content %}
<div class="login-container">
    <h2>Login</h2>
    <form method="post" action="{% url 'account_login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    <a href="{% url 'account_signup' %}">Sign Up</a>
</div>
{% endblock %}

issues/templates/issues/new.html
{% extends "issues/layout.html" %}

{% block title %}
New Page - Templates
{% endblock %}

{% block body %}
<form action="{% url 'new' %}" method="post">
    {% csrf_token %}
    <div>
        <input class="form-control" type="text" name="title" placeholder="Template Title" style="max-width: 60%;">
    </div>
    <hr>
    <textarea name="content"><div id="markdown-content">{{ entry|safe }}</div></textarea>
    <div>
        <input class="btn btn-primary" type="submit" value="Save">
    </div>
</form>
{% endblock %}

issues/templates/issues/not_found.html
{% extends "issues/layout.html" %}

{% block body %}
<h1>Not Found</h1>

There does not appear to be a page with the requested title.
{% endblock %}

issues/templates/issues/results.html
{% extends "issues/layout.html" %}

{% block body %}
<h1>Results</h1>

<p>
    Search Query: {{ query }}
</p>

<ul>
    {% for result in results %}
    <li>
        <a href="{% url 'entry' result %}">
            {{ result }}
        </a>
    </li>
    {% empty %}
    <li>No results for search query.</li>
    {% endfor %}
</ul>

{% endblock %}

issues/templates/issues/search.html
{% extends "issues/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
<div class="container mt-4">
    <h1 class="display-4 mb-4">Search</h1>
    <h2>"{{ title }}"</h2>
    {% if res %}
    <p>getBizzy does not have a template with this exact name. Titles on getBizzy are case sensitive. Below are some partial matches for "{{ title }}":</p>
    <ul>
        {% for item in res %}
        <li><a href="{% url 'entry' item %}">{{ item }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No matches found for "{{ title }}".</p>
    {% endif %}
</div>
{% endblock %}

issues/templates/issues/settings.html
{% extends "issues/layout.html" %}

{% block title %}
{{ Title }}
{% endblock %}

{% block body %}
<h1>Settings</h1>
<h2>Welcome, {{ user.username }}!</h2>
<form method="post">
    {% csrf_token %}
    <h3>Repository Settings</h3>
    {{ repo_form.as_p }}
    <h3>Issue Template Settings</h3>
    {{ template_form.as_p }}
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>
<!-- Example of listing existing repositories and templates -->
{% for repo in user.repositories.all %}
<div>{{ repo.repo_name }}</div>
<div>{{ repo.repo_url }}</div>
<!-- Add edit and delete buttons -->
<a href="{% url 'edit_repo' repo.id %}">Edit</a>
<a href="{% url 'delete_repo' repo.id %}">Delete</a>
{% endfor %}

{% for template in repo.issuetemplates.all %}
<div>{{ template.template_name }}</div>
<div>{{ template.content|truncatewords:20 }}</div>
<a href="{% url 'edit_template' template.id %}">Edit</a>
<a href="{% url 'delete_template' template.id %}">Delete</a>
{% endfor %}

{% endblock %}